version: "3"
services:
  node:
    build: .
    image: "code-fever/angular-app:latest"
    user: "node"
    container_name: angular-app
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - "4200:4200"
    command:
      - /bin/bash
      - -c
      - |
        ng new angular-app
        cd angular-app/
        npm install
        npm start
#  server:
#    image: "node:18"
#    container_name: server
#    working_dir: /home/node/app
#    volumes:
#      - ./server:/home/node/app
#    ports:
#      - "8080:8080"
#    command:
#      - /bin/bash
#      - -c
#      - |
#        npm install ws
#        node server.mjs
